Repository gitpod-samples/Gitpod-Raycast-Extension, pull requests merged in 2023-03, with the labels that each got.

#27 [feat] GitHub OAuth added for simpler auth
  assets/Icons/gh-icon.png
  assets/Icons/gh-icon@dark.png
  package.json
  src/api/oauth.ts
  src/helpers/withGithubClient.tsx
Labels: enhancement, Convenience

#24 [feat] Gitpod samples templates now in Raycast
  package.json
  src/api/repository.graphql
  src/components/TemplateListEmptyView.tsx
  src/components/TemplateListItem.tsx
  src/generated/graphql.ts
  src/open_template.tsx
Labels: enhancement, new feature

#23 Github Asset preview in the extension itself 🧑‍🚀
  src/api/issue.graphql
  src/api/pullRequest.graphql
  src/components/BranchListItem.tsx
  src/components/IssueListItem.tsx
  src/components/PullRequestListItem.tsx
  src/generated/graphql.ts
  src/open_repo_context.tsx
Labels: enhancement, new feature, Convenience
